#!/bin/bash
if [ ! $# -eq 0 ]; then
	echo "Run without arguments."
	exit 1
fi
	
cd testing
../mdpdf.py -c
rm -f test.pdf
../mdpdf.py test.md header_simon >> ../log.txt
if [ -f "test.pdf" ]; then
    echo "Nothing broke!"
	rm -f ../log.txt
else
    echo "Something broke. Check log.txt."
fi
